name: CI

on:
  push:
  pull_request:
    branches:
      - main

env:
  image: ghcr.io/sushiibot/sushii-analytics

jobs:
  docker-build:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get short SHA
        id: sha
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.image }}:latest
            ${{ env.image }}:${{ steps.sha.outputs.sha_short }}
          cache-from: type=registry,ref=${{ env.image }}:buildcache
          cache-to: type=registry,ref=${{ env.image }}:buildcache,mode=max
